brianc/node-sql

- lib/node/query.js
- package.json
- test/dialects/insert-tests.js
Fix for insert statement with empty array without object i.e. []. currently it is issuing select * from table_name in this case.
For array with empty object, it will behave as default.
> To handle cases where an insert statement is created with empty insert data

- lib/node/query.js
- test/dialects/where-clause-tests.js
Noticed that there wasn't complete coverage for Microsoft SQL Server in the tests. I'm sure I'll be finding a number of these since I added the Microsoft stuff quite a while ago and things have changed.
> Updated some tests to include coverage for Microsoft SQL Server (and other change).

- lib/dialect/mssql.js
- test/dialects/in-clause-tests.js
- test/dialects/not-in-clause-tests.js
This adds support for the NOT IN clause. IN was already handled.
Updated test cases for MSSQL and IN clauses and NOT IN clauses.
> - Fixed issue with MSSQL NOT IN clause.

- test/dialects/case-tests.js
The syntax is the same as the other flavors so no real modifications to the code generator where necessary.
Also cleaned up some trailing commas in the existing test cases just to make this file more consistent with the other ones that don't have the trailing commas.
> Added test cases for Microsoft SQL Server CASE statement. 

- lib/functions.js
> Fixed a bug COALESC->COALESCE

- lib/dialect/postgres.js
> Add _visitingJoin check to visitColumn.

- README.md
> readme: mention dialects

- lib/dialect/postgres.js
- package.json
- test/dialects/join-tests.js
- test/dialects/literal-tests.js
- test/dialects/subquery-tests.js
add missing quote when using named subquery
> add quote to named subquery alias

- lib/dialect/postgres.js
- test/dialects/create-table-tests.js
in a table column definition, when a foreign key is referenced, allows ON DELETE CASCADE/ON DELETE RESTRICT constraints.
> adding on-delete constraints to create table

- lib/dialect/postgres.js
- test/dialects/subquery-tests.js
The current results for this are somewhat nonsensical. I think this is quite a bit nicer! :)
> Allow passing plain query as subquery.

- lib/dialect/postgres.js
Put onDelete in a variable and only call #toUpperCase once. Also, fix up some strange indentation.
> Simplify onDelete conditional.

- lib/node/valueExpression.js
- test/dialects/alias-tests.js
notBetween translates to "NOT BETWEEN ? AND ?" sql
> Added notBeteen dialect

- lib/table.js
- test/table-tests.js
It's quite handy to call `#limit` directly from the table. :smiley_cat: What do you think?
> Add limit function to tables.

- lib/node/query.js
- test/dialects/subquery-tests.js
Inner join could be mimicked using multiple from statements and a where clause, but I couldn't figure out how to get my subquery to be on the left side of a left join.
> Add left-join support to subQuery

- lib/dialect/postgres.js
- test/dialects/insert-tests.js
This reverts commit 7a640319d304f4f70ef831ca60050226a93f73c6, reversing
changes made to cbd17ea230fb21c56aa7c19115d3ccbd7f9431a5.
> Revert "Merge pull request #290 from ericjperry/master"

- lib/dialect/postgres.js
@brianc, 
fix for the jshint error.
> jshint-fix: fix for jshint error

- lib/dialect/mssql.js
- lib/dialect/mysql.js
- lib/dialect/postgres.js
- lib/dialect/sqlite.js
- lib/functions.js
- test/dialects/date-tests.js
Added support for some basic date functionality that is supported by the major DBMSs.
> Add support for basic date functions

- lib/dialect/postgres.js
Since we just need to know if this value is a Date, we can check it directly.
> Check instanceof Date.

- lib/dialect/postgres.js
- lib/dialect/sqlite.js
- lib/node/orIgnore.js
- lib/node/query.js
- test/dialects/insert-tests.js
Tests pass. Addresses issue #237 
Followed example from https://github.com/brianc/node-sql/commit/f9c9d2a7e0ae43de3943f9fe6afa39b8c2f4bc12
> add OR IGNORE for sqlite

- .travis.yml
- lib/dialect/mssql.js
- lib/dialect/oracle.js
- lib/dialect/postgres.js
- lib/node/join.js
- lib/table.js
- test/dialects/join-tests.js
Adds support for Postgres "left join lateral" which translates to Microsoft SQL Server and Oracle  "outer apply".
> Support for "left join lateral" / "outer apply"
