lib/node/where.js
test/dialects/where-clause-tests.js

If the where clause is created dynamically it could be the case that it's empty. With this patch a dummy clause (1 = 1) is created in that case to avoid errors.

support empty array where clause

---

lib/dialect/postgres.js
test/dialects/select-tests.js

If .start() is used with a table definition that contains aliases, only the first column contains the table/schema name. This patch adds the table/schema prefix to all columns.

fixed missing table name for .star() with alias case

---

lib/table.js
test/table-tests.js

Our application makes heavy use of schemas and we needed a way to clone tables. So this is a quick stab at it, but someone who is familiar with the projects codebase should look over it. 
Also fixes half of #198 I think.

Add method table.clone([config])

---

lib/node/query.js
lib/table.js
test/dialects/insert-tests.js

Regarding  https://github.com/brianc/node-sql/pull/197, As suggested by @spion This patch will override previous fix and will return with harmless select statement with "WHERE (1=2)"

Harmless select in case of invalid insert attempt

---

lib/dialect/mssql.js
test/dialects/case-tests.js

There was an issue with the implementation of a simple case statement in SQL Server. This syntax
```sql
SELECT CASE WHEN true THEN 1 END FROM xxx
```
is not supported in SQL Server. Not only is `true` not a valid keyword, but you have to use an actual expression like `1=1` (you can't just say WHEN 0, for example).
I've modified the code to output `1=1` for true values and `0=1` for false values.
I've updated the tests to reflect the new changes.

Microsoft SQL Server CASE Statement Updates

---

lib/dialect/postgres.js
test/dialects/create-table-tests.js
test/dialects/support.js

Fix a bug that added all columns as composite primary keys (instead of just those with `primaryKey: true`).
Also removed 'query result' from the assert so that more information is given when tests fail (i.e. the expected and retrieved queries).

Fix composite primary key bug

---

lib/dialect/mssql.js
lib/dialect/mysql.js
lib/dialect/sqlite.js
lib/functions.js
lib/node/valueExpression.js
test/binary-clause-tests.js
test/dialects/matches-test.js

I need to perform text search queries for my project (using Postgres).  
Here is what i think is needed to perform such queries.  I'm not very familiar yet with your module, please forgive newbie mistakes.
I added the "match" operator (`@@`) to perform text search on a column (`tsvector`).  I also added the standard text search functions to make possible to make a complete query. 
I don't use Mysql, Mssql nor sqlite.  The implementation is based on the documentation I found.

add match operator for text search

---

package.json
runtests.js
test/mocha.opts

@lebolo comment on #133 got me thinking about how to make this run cross platform without the user having to do anything special. I first tried changing the test script in the package.json to
```
...
"scripts": {
"test": "mocha"
},
...
``` 
which worked well, except the NODE_ENV was not set to "test". I couldn't figure to any way to get it set in a cross-platform way without writing a NodeJS script. Which is essentially what this pull request contains.
I've tested it on both Windows and OSX and it seems to work. But it would be nice to have someone else check it out.
Also, it requires NodeJS v0.12 since it uses the `childProcess.execSync` function.
This pull request also modifies the mocha.opts file to default the output to "dot" mode. This is the output that I was always seeing since I …

Cross-Platform Testing

---

lib/dialect/postgres.js

Previously duplicated the check for `columnNode.references.table`.

Minor bug fix to assert existence of references column

---

lib/dialect/mssql.js
test/dialects/insert-tests.js

**Please review pull request #218 first since it will make some of these tests fail**
Right now we are throwing an exception for the RETURNING statement since it's not implemented in MS SQL the same way as PostgreSQL. In MS SQL it is the OUTPUT clause but it appears before the VALUES in the syntax. When I have some more time, I'll try to implement it correctly. But at least there are tests for all the INSERT statements that are currently supported.

Added insert-tests for Microsoft SQL Server.

---

lib/dialect/postgres.js
test/column-tests.js
test/dialects/ilike-tests.js
test/dialects/insert-tests.js

Currently, if you attempt a statement like:
```javascript
var  query=post.insert(post.content,post.userId).select(user.id).from(user).where(user.name.equals("joe")
```
It will generate
```sql
INSERT INTO "post" ("content", "userId") SELECT "id" FROM "user" WHERE ("name" = 'joe')
```
This works fine, until the SELECT statement includes a JOIN at which point the field names need to be qualified. This pull request makes the previous query generate this:
```sql
INSERT INTO "post" ("content", "userId") SELECT "user"."id" FROM "user" WHERE ("user"."name" = 'joe')
```
The only tests inside the insert-tests.js file I changed are ones that deal with SELECT after the insert. So I'm pretty sure I didn't break any other forms of insert.
The other test that I had to change was the "respects AS rename …

Fixes issue with INSERT statements using a SELECT

---

test/dialects/insert-tests.js

I started fixing some of the `INSERT FROM SELECT + JOIN` test cases for mssql with prefixing table columns, but I hit a snag on one final test. @danrzeppa would you be able to check this one out?

Start fixing 216 tests

---

lib/dialect/mssql.js
lib/dialect/postgres.js
lib/node/create.js
lib/node/query.js
lib/table.js
test/dialects/create-table-tests.js

Adding support for temporary tables as requested in issue #188.
Everything works well with the *standard* SQL implementations (PostgreSQL, MySQL, SQLite). This pull request even works for Microsoft SQL Server, except that I can't seem to figure out how to get the tests to run correctly.
In MS SQL temporary tables are defined by placing a "#" before the table name. So in MS SQL
```sql
CREATE TABLE #test
```
is equivalent to PostgreSQL
```sql
CREATE TEMPORARY TABLE test
```
Whenever the temp table is referenced it needs to be preceded by "#".
So what I wanted to do, as you can see in the changes, is modify the Table.getName function to prepend the "#". I tried to do this by looking at the dialectName of the table. This works ok, if you start your app off like:
```javascript
var …
```

Support for temporary tables.

---

lib/dialect/postgres.js
test/dialects/indexes-tests.js

there that should be much more readable
since the last pr caused some confusion when i kept the old syntax for mysql and sqlite, i made the change simpler by changing it for all dialects.

fixes drop index statement for pg

---

lib/dialect/postgres.js
lib/dialect/sqlite.js
lib/node/query.js
lib/node/truncate.js
lib/table.js
test/dialects/truncate-table-tests.js

Adds the TRUNCATE TABLE command. I believe I have the syntax is correct for all currently supported databases. Generates
```
TRUNCATE TABLE name
````
Where name is appropriately quoted for the engine. For PostgreSQL, MySQL, Microsoft SQL. For SQLite it generates
```
DELETE FROM name
```
since SQLite doesn't have a TRUNCATE command.

Added TRUNCATE TABLE command.

---

lib/dialect/mssql.js
lib/dialect/postgres.js
lib/node/distinct.js
lib/node/query.js
lib/node/select.js
test/dialects/distinct-tests.js
test/dialects/insert-tests.js

This resolves the DISTINCT issue described in #226 where DISTINCT currently only works on one column. With this change it is possible to
```
var query=posts.select(post.id,post.user).distinct()
```
which will generate (properly quoted)
```
SELECT DISTINCT post.id, post.user FROM post
```
I believe this generates correct SQL for all four currently supported dialects.
I did not make any changes to the current way distinct works on columns.
I also re-factored some common code out of the mssql module so that it can be better shared.

Added proper DISTINCT functionality.

---

lib/dialect/mssql.js
test/dialects/alter-table-tests.js

I changed the commented code, adding apostrophes to the original column name, since this is also supported for MSSQL. 
This way, the generated rename statement will be something like this:
- exec sp_rename '[group].[userId]', [newUserId], 'column'
Also changed the tests to reflect this change.

Implemented Rename Columns for MSSQL

---

lib/dialect/mssql.js
test/dialects/function-tests.js

Microsoft SQL Server uses LEN instead of LENGTH. This pull request fixes it.
I've added a function-tests.js file to the test/dialects directory to validate that the existing code still works. This file could be expanded to include tests for all the common functions across all dialects.

MSSQL LENGTH function fix

---

lib/dialect/postgres.js
lib/node/distinctOn.js
lib/node/query.js
test/dialects/binary-clause-tests.js
test/dialects/distinct-on-tests.js

An alias/"AS" in a binary clause causes an error. This patch set's the property value to the name value to prevent an alias in the SQL query.

don't use alias in binary clause

---

lib/functions.js
lib/index.js

From what I can tell, the sql instance is never accessed from a function call. Seems like we can just drop it!

Function calls don't need the sql instance.

---

lib/dialect/sqlite.js
lib/functions.js
test/dialects/function-tests.js

This adds the LEFT and RIGHT string functions. These are standard functions in PostgreSQL, MySQL, Microsoft SQL Server and Oracle. These functions don't exist in SQLite so this pull request converts them into a call to SUBSTR. For example,
```javascript
var sql=require("sql")
var leftQuery=post.select(sql.functions.LEFT(post.content,4))
var rightQuery=post.select(sql.functions.RIGHT(post.content,4))
```
in all dialects except SQLite will generate
```sql
SELECT LEFT("post"."content",4) FROM "post"
SELECT RIGHT("post"."content",4) FROM "post"
```
but in SQLite will generate
```sql
SELECT SUBSTR("post"."content",1,4) FROM "post"
SELECT SUBSTR("post"."content",-4) FROM "post"
```

Added LEFT and RIGHT functions.

---

lib/dialect/postgres.js
lib/node/createView.js
lib/node/query.js
test/dialects/create-view-tests.js

Hi.
As proposed in #245, I implemented a Create View support. The idea is that any select query can be turned into a view by calling the ```createView``` method.
So, an example of use would be:
```javascript
var sql = require('sql');
var user = sql.define({
name: 'user',
columns: ['id', 'name']
});
var query = user.select(user.star()).where(user.id.equals(1));
var view = query.createView('myView');
var text = view.toQuery();
```
This returns a query object as folows. Note that since we are creating a view, the parameters are replaced with its values.
```javascript
{
text: 'CREATE VIEW "myView" AS SELECT "user".* FROM "user" WHERE ("user"."id" = 1)',
values: [] 
}
```
Any doubts, just get in touch...

Adds Create View Support - closes #245

---

lib/node/query.js
test/dialects/returning-tests.js

See #272
I wasn't able to find any tests for `returning` in particular, so I added second one to make sure nothing breaks (passing in an expression like `user.id.as('user_id')` also worked as expected, but that felt like too much to include).
Editor cleaned up some trailing whitespace by accident. "Oops"…

returning() defaults to '*'

---

lib/dialect/sqlite.js
lib/index.js
lib/node/index.js
test/dialects/support.js
test/dialects/tostring-tests.js

We ran into a problem where we were inserting data into SQLite as a timestamp in development, and as a timestamp with time zone. When attempting to query for that data, the current default in the sqlite dialect is to call .toISOString() on the date object, which will only work if the user has stored all of their data in SQLite as ISO strings (since it will just do a lexicographic comparison).
With this update, Date objects are detected and the epoch milliseconds are used for comparisons if the user provides a configuration object denoting that they would like to perform this conversion. This introduces the concept of a configuration object for the dialects...which is a departure from how they were being used before. If anyone has suggestions on how to handle this differently, please let …

Added configurability for dialects

---

lib/dialect/mssql.js
lib/dialect/mysql.js
lib/dialect/oracle.js
lib/dialect/postgres.js
test/dialects/order-tests.js

Since the configuration object is now available to each dialect, I have added a configuration for postgres allowing the user to specify that NULLS should appear in a specific order. This is achieved through the 'NULLS FIRST'/'NULLS LAST' operators described [here](http://www.postgresql.org/docs/9.4/static/queries-order.html). We ran into an issue where nulls were returned in different orders between databases, and Postgres seems to be the odd man out with the ability at query time to control where NULLs land. This configuration allows us to achieve consistency across DBMS.

Added configuration for postgres dialect so that null order can be expressed

---

lib/dialect/postgres.js
test/dialects/subquery-tests.js

There was a bug with the new sqlite date format configuration.  The config wasn't being passed down to the subquery.  Added a test case that failed before this fix was applied.
@ericjperry

Fixed passing config to subquery

---

lib/dialect/postgres.js
test/column-tests.js

In the instance of a table with a column value of "alias" [word.replace](https://github.com/brianc/node-sql/blob/master/lib/dialect/postgres.js#L192) will error due to "alias", at this point, is an object.
A slight modification to the property check [here](https://github.com/brianc/node-sql/compare/master...iamcharliegoddard:fix-alias-as-column-name#diff-441b873f400aa79e8bd24fb525f0fb1cR732) from:
```JavaScript
if(table.alias) {
txt.push(this.quote(table.alias));
} else {
}
```
to
```JavaScript
if(typeof table.alias === 'string') {
txt.push(this.quote(table.alias));
} else {
}
```
Seems to have remedy the issue.
Thoughts?

Tables with "alias" as a column name error on word.replace

---

lib/dialect/mssql.js
test/index-tests.js

Adds ability to override the default parameter place holder of @index and use ? instead. Addresses #285.
This can be used by adding `questionMarkParameterPlaceholder:true` to the config when setting the dialect like so:
```
var sql = require("sql")
sql.setDialect("mssql",{questionMarkParameterPlaceholder:true})
```

Use ? for placeholder in mssql dialect

---

lib/dialect/postgres.js
lib/dialect/sqlite.js
test/dialects/case-tests.js
test/dialects/update-tests.js

Sqlite doesn't support TRUE and FALSE as boolean values, only 1 and 0.
Also, if trying to update using a JSON object, if the object didn't have an explicit .toString() method, it would end up trying to save '[object Object]' to the database.  Switched out to use JSON.stringify in that case.

Fix booleans and objects

---

lib/dialect/postgres.js
test/dialects/insert-tests.js

Postgres supports arrays natively, but they were not being created properly with the handling of arrays in the Postgres dialect. According to the [current documentation](http://www.postgresql.org/docs/current/static/arrays.html) arrays are wrapped as a string (single quoted), with brackets, and each string (if the elements are strings) is double quoted. This PR updates the handling of arrays (for Postgres only) to match what the db expects.

Fixed PostgreSQL array insertion syntax.

---

lib/dialect/postgres.js
test/dialects/insert-tests.js
test/dialects/update-tests.js

@brianc I figured out the issue with the tests. @barryhammen had added some tests for arrays and modified the way that arrays were serialized with SQLite, which threw off a couple of my tests. I also found that the way arrays of objects were being serialized was not supported by postgres, so I've added a little bit of logic to check if the array being serialized is an array of objects, and if so just giving it to postgres as a JSON.stringified array (which is valid). This check is pretty naive and doesn't work for situations where you have a complex and deeply nested array of objects, but I think it handles the 99% use case.
Let me know what you think!

Second attempt at fixing Postgres arrays

---

lib/dialect/postgres.js
lib/table.js

I'm open to other ideas besides `NODE_ENV=debug`, but having it print stuff out to the console by default is incredibly annoying, especially when you can't change the names of your columns.

No console logging

---

lib/dialect/postgres.js
lib/node/index.js
lib/node/query.js
test/dialects/select-tests.js

These changes allow for the writing of statements like:
```javascript
var sql=require("sql")
var query=sql.select(a.select(a.col.sum()).plus(b.select(b.col.sum()))
```
which generates:
```sql
SELECT (SELECT SUM(a.col) FROM a) + (SELECT SUM(b.col) FROM b)
```
A side effect is that it also allows for writing `SELECT ` statements without a from clause like:
```javascript
var query=sql.select("1")
```
which generates:
```sql
SELECT 1
```

Extend query with value expressions

---

lib/dialect/postgres.js
test/dialects/insert-tests.js

Before this pull request, this code
```javascript
var query=post.insert(post.id)
var select=user.select(user.id)
query.add(select)
```
would generate (properly quoted)
```sql
INSERT INTO post (id) (SELECT user.id FROM user)
```
Notice the parentheses around the `SELECT` clause. In many cases, this isn't a problem, but in Microsoft SQL server, when you try to add an `ORDER BY` clause onto your select, it is a syntax error  when there are parentheses around the `SELECT` statement.
This pull request makes the above query generate:
```sql
INSERT INTO post (id) SELECT user.id FROM user
```
which is exactly what is generated when you write the query like:
```javascript
var query=post.insert(post.id).select(user.id).from(user)
```
So it actually generates more consistent SQL regardless of the …

INSERT INTO ... SELECT create with .add()

---

lib/dialect/postgres.js
lib/node/foreignKey.js
lib/table.js
test/dialects/create-table-tests.js

Allows foreign keys which use muliple columns. This code:
```
var table1 = sql.define({
name: 'table1',
columns: [
{name: 'id', dataType: 'int'},
{name: 'ref1', dataType: 'text'},
{name: 'ref2', dataType: 'text'},
{name: 'text', dataType: 'text'}
]
});
var table2 = sql.define({
name: 'table2',
columns: [
{name: 'id', dataType: 'int'},
{name: 'ref', dataType: 'text'},
{name: 'data', dataType: 'text'}
],
foreignKeys: {
table: 'table1',
columns: ['id', 'ref'],
refColumns: ['id', 'ref1'],
onDelete: 'cascade'
}
});
console.log(table1.create().toQuery().text);
console.log(table2.create().toQuery().text);
```
produces this output:
```
CREATE TABLE "table1" ("id" int, "ref1" text, "ref2" text, "text" text)
CREATE TABLE "table2" ("id" int, "ref" text, "data" text, FOREIGN KEY ( "id", "ref" ) …
```

Add table level foreign keys

---

lib/dialect/sqlite.js
test/dialects/date-tests.js

Via configuration you can set SQLite to use epoch timestamps or ISO formatted dates.  The original implementation only worked for ISO formatted dates.  This PR fixes that.

Fix sqlite date functions for epoch

---

lib/dialect/postgres.js

This file already uses `Array.isArray` in several other places. This just makes it consistent! :)

_.isArray -> Array.isArray

---

lib/dialect/mysql.js
test/dialects/aggregate-tests.js

MySQL doesn't accept count(`table`.*) syntax.  Changed to count(*) by blagging code from MSSQL dialect.

Use count(*) syntax for MySQL instead of count(`table`.*)

---

lib/dialect/mssql.js
lib/dialect/mysql.js
lib/dialect/oracle.js
lib/dialect/postgres.js
lib/dialect/sqlite.js
lib/node/onConflict.js
lib/node/query.js
test/dialects/insert-tests.js

PostgreSQL supports upserts by ON CONFLICT clause provided
in versions 9.5 and above. This should fix issue #333

Add support for ON CONFLICT as a support for upserts in PostgreSQL

---

lib/dialect/oracle.js
test/dialects/alter-table-tests.js

This PR addresses https://github.com/brianc/node-sql/issues/332 by changing the way the SQL statement is generated when adding/dropping tables using the Oracle dialect.

Fix adding/dropping columns with Oracle

---

lib/table.js
test/dialects/insert-tests.js
test/dialects/support.js

This PR resolves https://github.com/brianc/node-sql/issues/323 by only changing the statement into a select if arguments doesn't exist or if it is an empty array. If arguments just an object then an insert statement is generated.

Fix calling insert with an object that has a length property

---

lib/table.js
test/table-tests.js

There was a bug which caused Table.hasColumn to return false when passed a property name (defined via column.property) instead of a column name.
This now works and all tests pass:
``` javascript
test('hasColumn with user-defined column property', function() {
var table = Table.define({
name: 'blah',
columns: [{
name: 'id',
property: 'theId'
}, {name: 'foo'}]
});
assert.equal(table.hasColumn('id'), true);
assert.equal(table.hasColumn('theId'), true);
});
```

Fix Table.hasColumn for columns with custom property names

---

lib/column.js
lib/dialect/postgres.js
lib/node/column.js
test/dialects/create-table-tests.js

I might have overlooked something blindingly obvious, but I couldn't find any way of setting the default value of a column when creating a table.  This pull request adds a defaultValue parameter which does just that.
Synopsis:
```
var table = sql.define({
name: 'test',
columns:
[
{
name: 'id',
dataType: 'int',
primaryKey: true
},
{
name: 'favourite_vegetable',
dataType: 'text',
defaultValue: 'cauliflower'
}
]
});
```
Produces the table creation query
```
CREATE TABLE "test" ("id" int PRIMARY KEY, "favourite_vegetable" text DEFAULT 'cauliflower')
```

Setting default values

---

lib/types.d.ts
package.json

This PR adds types that guide user from `sql.define` to table objects, and type-helped use of those. Related issue is #351 
Definition file is very useful, yet isn't 100% incomplete, as only `sql.define` is added to types, while there are other things in the module. SQL is vast, so is node-sql (superb job :+1: ), hence, 100% coverage with types is a task. But I already use these types in production. Can we say that 80% is already here?
Definitions can be a place for comments that people will read, thanks to mature TS's tooling (VSCode, etc.). So, definitions can be added. It can be done gradually.

Adding types v1

---

lib/types.d.ts

- add a new type definition: SQLDialects as Union of strings.
- add function `setDialect`
- add `dialect` property to `TableDefinition` interface
Issue #351

Typescript definition for SQL Dialects

---

lib/node/query.js
test/dialects/order-tests.js

Calling `order` with an empty array generates 'ORDER BY' without any sort expression. This PR checks for empty array and skip 'ORDER BY' generation if necessary.

Fix order method with empty array generates invalid SQL

---

lib/functions.js
lib/index.js
test/function-tests.js

Syntax: 
```
Foo.select(sql.function('CUSTOM_FUNCTION)(Foo.baz))
SELECT CUSTOM_FUNCTION("foo"."baz") FROM "foo";
```
This allows users to extend node-sql's capabilities to whatever unsupported or custom functions they wish to use.

Exposes function creation to allow use of unsupported functions

---

.travis.yml
lib/index.js
test/dialects/subquery-tests.js

Adds abilty to create a SubQuery without starting with a table. For example:
```javascipt
var sql=require("sql")
var subQuery = sql.subQuery().select(user.id).from(user)
var query=post.select().where(post.user_id.in(subQuery))
```
In this example, the ```subQuery``` could have been defined as ```user.subQuery().select()```, but there are instances when dynamically generating SQL where you may not have the table at the time you want to create the subquery.

Top-Level SubQuery support
